<template>
  <div class="ech">
    <!-- <div v-for="(item, index) in content" :key='index'>
      {{item.randomId}}
      <div :id="item.randomId" style="width:500px;height:400px"></div>
    </div> -->
      <div id='kkkkk0' style="width:500px;height:400px"></div>
      <div id='kkkkk1' style="width:500px;height:400px"></div>
    
  </div>
</template>

<script>
import * as echarts from 'echarts';
import { color } from 'echarts';
import {echartTEMP} from '../../utils/echartTEMP'
export default {
  name: 'echart5',
  data(){
    return{
      value:[
        {
          "type":2,
          "value":{
              "leftUnit":null,
              "titleShow":true,
              "lowList":null,
              "xshowType":1,
              "unit":"%",
              "chartName":"新增居民贷款部门构成",
              "chartTitle":"<b>图<font face=\"Arial\">3</font>：新增居民贷款构成占比</b>",
              "chartType":5,
              "skipType":2,
              "sourceShow":true,
              "x":{
                  "values":[
                      "2017-01",
                      "2017-02",
                      "2017-03",
                      "2017-04",
                      "2017-05",
                      "2017-06",
                      "2017-07",
                      "2017-08",
                      "2017-09",
                      "2017-10",
                      "2017-11",
                      "2017-12",
                      "2018-01",
                      "2018-02",
                      "2018-03",
                      "2018-04",
                      "2018-05",
                      "2018-06",
                      "2018-07",
                      "2018-08",
                      "2018-09",
                      "2018-10",
                      "2018-11",
                      "2018-12",
                      "2019-01",
                      "2019-02",
                      "2019-03",
                      "2019-04",
                      "2019-05",
                      "2019-06",
                      "2019-07",
                      "2019-08",
                      "2019-09",
                      "2019-10",
                      "2019-11",
                      "2019-12",
                      "2020-01",
                      "2020-02",
                      "2020-03",
                      "2020-04",
                      "2020-05",
                      "2020-06",
                      "2020-07",
                      "2020-08",
                      "2020-09",
                      "2020-10",
                      "2020-11",
                      "2020-12",
                      "2021-01"
                  ]
              },
              "rightUnit":null,
              "y":[
                  {
                      "stack":0,
                      "color":"#1362B0",
                      "pos":null,
                      "lineType":1,
                      "values":[
                          "16.3",
                          "-26.7",
                          "43.3",
                          "22.2",
                          "29.2",
                          "35",
                          "19.1",
                          "32.6",
                          "34.6",
                          "17.6",
                          "32.7",
                          "5.5",
                          "34.4",
                          "-17",
                          "35",
                          "32.9",
                          "36.1",
                          "33.8",
                          "27.9",
                          "37",
                          "42.1",
                          "33.8",
                          "33.1",
                          "33.1",
                          "29.6",
                          "",
                          "48.3",
                          "20.8",
                          "29.4",
                          "35.4",
                          "13.6",
                          "30.6",
                          "35.4",
                          "14.8",
                          "31.4",
                          "25.3",
                          "-18.1",
                          "109",
                          "52.1",
                          "34.2",
                          "33.8",
                          "34.9",
                          "19.9",
                          "33.8",
                          "34.8",
                          "6.3",
                          "33",
                          "20.6",
                          "25.8"
                      ],
                      "cutlineName":"短期",
                      "id":14,
                      "showNew":true,
                      "formatList":null,
                      "cutlineShow":1
                  },
                  {
                      "stack":0,
                      "color":"#B2B2B2",
                      "pos":null,
                      "lineType":1,
                      "values":[
                          "83.7",
                          "126.7",
                          "56.7",
                          "77.8",
                          "70.8",
                          "65",
                          "80.9",
                          "67.4",
                          "65.4",
                          "82.4",
                          "67.3",
                          "94.5",
                          "65.6",
                          "117",
                          "65",
                          "67.1",
                          "63.9",
                          "66.2",
                          "72.1",
                          "63",
                          "57.9",
                          "66.2",
                          "66.9",
                          "66.9",
                          "70.4",
                          "",
                          "51.7",
                          "79.2",
                          "70.6",
                          "64.6",
                          "86.4",
                          "69.4",
                          "64.6",
                          "85.2",
                          "68.6",
                          "74.7",
                          "118.1",
                          "-9",
                          "47.9",
                          "65.8",
                          "66.2",
                          "65.1",
                          "80.1",
                          "66.2",
                          "65.2",
                          "93.7",
                          "67",
                          "79.4",
                          "74.2"
                      ],
                      "cutlineName":"中长期",
                      "id":15,
                      "showNew":true,
                      "formatList":null,
                      "cutlineShow":1
                  }
              ],
              "chartSource":"资料来源：<font face=\"Arial\">WIND</font>、招商银行研究院"
          }
        },
        {
          "type":2,
          "value":{
              "leftUnit":null,
              "titleShow":true,
              "lowList":null,
              "xshowType":1,
              "unit":"%",
              "chartName":"新增非金融企业部门贷款构成",
              "chartTitle":"<b>图<font face=\"Arial\">4</font>：新增非金融企业贷款构成占比</b>",
              "chartType":5,
              "skipType":2,
              "sourceShow":true,
              "x":{
                  "values":[
                      "2017-01",
                      "2017-02",
                      "2017-03",
                      "2017-04",
                      "2017-05",
                      "2017-06",
                      "2017-07",
                      "2017-08",
                      "2017-09",
                      "2017-10",
                      "2017-11",
                      "2017-12",
                      "2018-01",
                      "2018-02",
                      "2018-03",
                      "2018-04",
                      "2018-05",
                      "2018-06",
                      "2018-07",
                      "2018-08",
                      "2018-09",
                      "2018-10",
                      "2018-11",
                      "2018-12",
                      "2019-01",
                      "2019-02",
                      "2019-03",
                      "2019-04",
                      "2019-05",
                      "2019-06",
                      "2019-07",
                      "2019-08",
                      "2019-09",
                      "2019-10",
                      "2019-11",
                      "2019-12",
                      "2020-01",
                      "2020-02",
                      "2020-03",
                      "2020-04",
                      "2020-05",
                      "2020-06",
                      "2020-07",
                      "2020-08",
                      "2020-09",
                      "2020-10",
                      "2020-11",
                      "2020-12",
                      "2021-01"
                  ]
              },
              "rightUnit":null,
              "y":[
                  {
                      "stack":0,
                      "color":"#1362B0",
                      "pos":null,
                      "lineType":1,
                      "values":[
                          "28.9",
                          "48.5",
                          "54.2",
                          "32.4",
                          "45.8",
                          "39.9",
                          "19",
                          "14.9",
                          "-11.6",
                          "-6",
                          "4.1",
                          "-39.9",
                          "21.6",
                          "19.5",
                          "15.6",
                          "13.6",
                          "-12",
                          "27.2",
                          "-16.6",
                          "-30.3",
                          "16.5",
                          "-83.4",
                          "-2.5",
                          "-17.2",
                          "23.6",
                          "17.8",
                          "29.1",
                          "-43.2",
                          "24.9",
                          "48.3",
                          "-79.3",
                          "-5.6",
                          "25.6",
                          "-94.1",
                          "25.4",
                          "0.8",
                          "27.6",
                          "57.8",
                          "42.8",
                          "-0.7",
                          "14.9",
                          "43.6",
                          "-95.8",
                          "0.8",
                          "13.7",
                          "-38.9",
                          "9.9",
                          "-53.9",
                          "23.3"
                      ],
                      "cutlineName":"短期",
                      "id":12,
                      "showNew":true,
                      "formatList":null,
                      "cutlineShow":1
                  },
                  {
                      "stack":0,
                      "color":"#B2B2B2",
                      "pos":null,
                      "lineType":1,
                      "values":[
                          "101.3",
                          "86.1",
                          "154.8",
                          "108.9",
                          "81.4",
                          "84.1",
                          "131.4",
                          "78.2",
                          "112.1",
                          "126.2",
                          "88",
                          "83.4",
                          "76.4",
                          "91.2",
                          "86.7",
                          "86",
                          "82.4",
                          "41.9",
                          "78.3",
                          "59.3",
                          "57.2",
                          "105.2",
                          "60",
                          "43.1",
                          "55.8",
                          "61.8",
                          "61.7",
                          "86.1",
                          "51.9",
                          "41.1",
                          "132.9",
                          "67.4",
                          "56.5",
                          "177",
                          "65",
                          "93.1",
                          "59.5",
                          "36.7",
                          "47.1",
                          "59",
                          "65.5",
                          "79.1",
                          "236.3",
                          "129",
                          "114.6",
                          "191.1",
                          "79.3",
                          "95.8",
                          "82.4"
                      ],
                      "cutlineName":"中长期",
                      "id":7,
                      "showNew":true,
                      "formatList":null,
                      "cutlineShow":1
                  },
                  {
                      "stack":0,
                      "color":"#A60922",
                      "pos":null,
                      "lineType":1,
                      "values":[
                          "-30.1",
                          "-34.6",
                          "-109",
                          "-41.3",
                          "-27.2",
                          "-24",
                          "-50.4",
                          "6.8",
                          "-0.5",
                          "-20.2",
                          "7.9",
                          "56.4",
                          "2",
                          "-10.7",
                          "-2.2",
                          "0.4",
                          "29.6",
                          "30.9",
                          "38.3",
                          "71",
                          "26.3",
                          "78.3",
                          "42.6",
                          "74.1",
                          "20.6",
                          "20.4",
                          "9.2",
                          "57.1",
                          "23.3",
                          "10.5",
                          "46.4",
                          "38.2",
                          "17.9",
                          "17.1",
                          "9.6",
                          "6.1",
                          "12.9",
                          "5.6",
                          "10.1",
                          "41.6",
                          "19.6",
                          "-22.6",
                          "-40.4",
                          "-29.8",
                          "-28.2",
                          "-52.2",
                          "10.8",
                          "58.2",
                          "-5.7"
                      ],
                      "cutlineName":"票据融资",
                      "id":3,
                      "showNew":true,
                      "formatList":null,
                      "cutlineShow":1
                  }
              ],
              "chartSource":"资料来源：<font face=\"Arial\">WIND</font>、招商银行研究院"
          }
        }
      ],
      content: [],
    }
  },
  mounted(){
    // 基于准备好的dom，初始化echarts实例
    this.$nextTick(() => {
      setTimeout(() => {
        this.init();
      }, 1000);
    });
  },
  methods: {
    init(){
      let newPromise = new Promise((resolve) => {
        resolve()
      })
      //然后异步执行echarts的初始化函数
      newPromise.then(() => {
        //	此dom为echarts图标展示dom
        this.draw()
      })
    },
    draw(){
      // var myChart = echarts.init(document.getElementById());
      this.content = echartTEMP(this.value);
      this.content.forEach((item,index) => {
        console.log(item)
        // item.eName = ""
        if(document.getElementById(`kkkkk${index}`)){
          item.eName = echarts.init(document.getElementById(`kkkkk${index}`));
          console.log(item.eName,'llllll')
          item.eName.setOption(item.option);
          window.addEventListener("resize", function () {
            if (item.eName) {
              item.eName.resize();
            }
          });
        }
      })
      // let a = echarts.init(document.getElementById(`kkkkk`));
      // console.log(a,'llllll')
      // a.setOption(item.option);
      console.log(this.content)
      // 绘制图表
      // myChart.setOption()
    }
  }
}
</script>

<style >
.ech{
  margin: 100px;
  display: flex;
  justify-content: space-between;
}
</style>